// @flow
export default [
  "active",
  "dirty",
  "dirtyFields",
  "dirtyFieldsSinceLastSubmit",
  "dirtySinceLastSubmit",
  "error",
  "errors",
  "hasSubmitErrors",
  "hasValidationErrors",
  "initialValues",
  "invalid",
  "modified",
  "modifiedSinceLastSubmit",
  "pristine",
  "submitting",
  "submitError",
  "submitErrors",
  "submitFailed",
  "submitSucceeded",
  "touched",
  "valid",
  "validating",
  "values",
  "visited",
];
