// @flow
export default [
  'active',
  'dirty',
  'dirtyFields',
  'dirtySinceLastSubmit',
  'error',
  'errors',
  'hasSubmitErrors',
  'hasValidationErrors',
  'initialValues',
  'invalid',
  'modified',
  'pristine',
  'submitting',
  'submitError',
  'submitErrors',
  'submitFailed',
  'submitSucceeded',
  'touched',
  'valid',
  'validating',
  'values',
  'visited'
]
